Avoid error due to ipv6 in maintenance ip
PrestaShop/dashactivity pull request #37
Opened 2023-05-16 13:12 UTC by NicolasCador

| Questions     | Answers
| ------------- | -------------------------------------------------------
| Description?  | Prestashop manages ip adresses for several needs. For exemple the class connection.php records the ip address in the database. This record is done with ip2long converting. ip2long manages only ipv4 adresses, so there is a 0 in the record. dashactivity module checks if connection ip is the same than the ones in the maintenance ip. If there is at least one ipv6 address in several maintenance ip adresses, the module doesn't show data on dashboard due to a sql error because there is ",," in the query.
| Type?         | bug fix 
| BC breaks?    | no
| Deprecations? | no
| Fixed ticket? | Fixes PrestaShop/Prestashop#31831.
| How to test?  | Put 1 ipv4 then 1ipv6 then 1 ipv4 in maintenance ip, save. Go to dashboard. you see data of visitors, carts, ... instead of only arrow turning

2023-05-16 13:26 UTC, mflasquin approved these changes

2023-05-16 13:27 UTC, mflasquin reviewed
Thanks for your contribution @NicolasCador, there is errors on the CI, can you fix them ?

2023-05-16 17:34 UTC, NicolasCador commented
Hi @mflasquin,

thank you.

I'm sorry, but the failed test should not, it's a tip from php.net:
<img width="850" alt="php array_filter strlen" src="https://github.com/PrestaShop/dashactivity/assets/96910631/40e3ded7-2118-4735-add3-2eb57648c58f">
 I propose to ignore the line.

2023-05-17 12:13 UTC, mflasquin requested changes

2023-05-17 12:13 UTC, mflasquin commented on dashactivity.php
> +            $maintenance_ips = implode(',', array_filter(array_map('ip2long', array_map('trim', explode(',', $maintenance_ips))),'strlen')); // @phpstan-ignore-line
```suggestion
            $maintenance_ips = implode(',', array_filter(array_map('ip2long', array_map('trim', explode(',', $maintenance_ips))), 'strlen'));
       
```

2023-05-17 15:14 UTC, mflasquin approved these changes

2023-05-17 22:59 UTC, NicolasCador commented
Hi @mflasquin,

wow, great!
How did you find the "\" solution to avoid failed test?

2023-05-19 10:58 UTC, AchrafKchaou1991 approved these changes
Hello @NicolasCador ,
I tested your Pr with PS1789 PS804 , it's LGTM
QA  ✅

[pr module.webm](https://github.com/PrestaShop/dashactivity/assets/131356155/02da662c-8dd8-41df-b3e2-dd1bc5df9c6b)

2023-05-19 13:10 UTC, merged

2023-05-19 13:10 UTC, nicosomb commented
Thank you @NicolasCador !